server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /ghostly/index.html;
    }

    location /ghostly {
        alias /usr/share/nginx/html/ghostly;
        try_files $uri $uri/ /ghostly/index.html;
        index index.html;
    }

    
}
