server {
    listen 80;

    location /ghostly {
        alias /usr/share/nginx/html/ghostly;
        try_files $uri $uri/ /ghostly/index.html;
        index index.html;
    }

    location / {
        return 301 /ghostly;
    }
}
